---
version: '3.5'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /data/jellyfin:/config
      - /data/jellyfin/tvseries:/data/tvshows
      - /data/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - WEBUI_PORT=8090
    volumes:
      - /data/qbittorrent/config:/config
      - /data/jellyfin/movies:/downloads
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
